---
name: Ethan Brockmann
address: "740 Hartwood, Brandon, MS 39042"
phone: (920) 728-5600
date: "`r format(Sys.Date(), '%B %Y')`"
email: "ethanbrockmann@gmail.com"
www: ethanbrockmann.com
github: EeethB
twitter: EeethB
angellist: ethan-brockmann
community: EeethB
output: vitae::awesomecv
aboutme: Full stack data analyst. Always looking for questions and answers in the data. Known for insightful questions, passionate efficiency, and clear communication. We all do our best work in environments that value diversity and inclusion of all kinds.
---

# Work Experience

**Actuarial Analyst, R Developer**. BlueCross BlueShield of Mississippi. Flowood, MS. June 2017 – Present 
  
  - Team lead on large group underwriting: Includes updating and streamlining old processes to be more transparent, accurate, and reproducible
  
  - Formerly team lead for EDGE server and risk adjustment: Included building new infrastructure for data reporting and quality assurance, as well as updating current processes to ensure accuracy and efficiency
  
  - Saved the company millions each year in risk adjustment transfers by ensuring quality in data submissions
  
  - Author and maintainer of an internal R package for safely interacting with the company's database
  
  - Mentored several more junior employees, training them in technical project details, documentation best practices, and workflow recommendations to ensure ownership of projects as well as smooth transitions to other analysts in the future
  
  - Built scalable big data reporting and visualization for company leadership using SQL, R, and Excel
  
  - Working knowledge of many statistical methods
  
**Actuarial Student Intern**. BlueCross BlueShield of Mississippi. Flowood, MS. May 2016 – August 2016 

  - Built a predictive model to find unreported risk in small group and individual populations
  
  - Presented technical capstone project to non-technical senior management

  - Assisted actuarial personnel in core actuarial functions

**Math Tutor**. Mississippi State University. Starkville, MS. November 2014 – December 2015 

  - Provided additional help to students in historically difficult classes 

  - Tutored students in algebra, trigonometry, calculus, linear algebra, basic mathematical proof classes, and chemistry 
  
  - Helped one student improve 30% from the first to the second test
   
**Rock Climbing Guide**. Mississippi State University. Starkville, MS. May - August 2015

  - Provided support, guidance, and belay services to patrons of the indoor climbing wall
  
  - Entrusted with opening and closing duties
  
**Soft Serve Specialist**. Frostie Freeze. Fort Atkinson, WI. March - October, 2009 - 2013

  - Took orders and payments, crafted treats, and performed behind-the-scenes cleaning and maintenance
  
  - Entrusted with opening and closing duties
  
  - Mentored less senior employees
  
**Field Worker**. AgVenture/Spangler Seedtech. Jefferson, WI. June - August, 2007 - 2013

  - Performed a variety of field work duties involving corn and soybeans
  
  - Supervised a team of other employees
  
# Side Projects

  - Author and maintainer of the [`edgedata`](https://github.com/EeethB/edgedata) package on CRAN
  
  - Proficient with Git and Github workflows, including completion of the fantastic [ooloo.io](https://ooloo.io/project/github-flow) tutorial, which gives the experience of working with Git in a team environment
  
  - Set up a Shiny Server instance using Docker to host interactive R Shiny applications
  
  - Experienced with Windows command line and Linux terminal
  
  - Familiarity with C, C++, HTML, CSS, \LaTeX
  
  - Passed actuarial exams P, FM, IFM, SRM, and LTAM

# Education

**Bachelor of Science in Mathematics**. Mississippi State University, Starkville, MS. GPA 3.9/4.0. May 2017 

  - Minor in Computer Science
  
  - Undergraduate research project in graph theory working with the independence polynomials of claw free graphs and trees: https://osebje.famnit.upr.si/~russ.woodroofe/ethan-brockmann.pdf 

  - Split level user interface design class included building a real-use interface design for Fedex using Python
  
  - Grader, Math tutor, MSU Outdoor Adventures, and Starkville Russian Club

# Other Skills

 - Attention to detail
 
 - Strong technical review skills
 
 - Experience working remote
 
 - Independent and driven
 
 - 4 years of high school Spanish, 4 semesters of college Russian, previously fluent in Lithuanian
 